import{i as l,S as L}from"./assets/vendor-46aac873.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const m=document.getElementById("gallery"),w=document.getElementById("form"),y=document.getElementById("input"),S=document.querySelector(".btn-load-more");document.querySelector(".loader");const s={key:"41508094-b690cca5e0d97ff8185874dce",q:"kat",image_type:"photo",orientation:"horizontal",safesearch:"true",page:1,per_page:40};let p=s.page,u=s.per_page,f;w.addEventListener("submit",e=>{e.preventDefault();const o=y.value.trim();o?(s.q=o,s.page=1,s.per_page=u,h(),b(),v()):l.info({position:"bottomCenter",message:"Please enter a search term."})});S.addEventListener("click",e=>{e.preventDefault(),b();const o=y.value.trim();o?(s.q=o,s.page+=1,s.per_page=u,h()):l.info({position:"bottomCenter",message:"Please enter a search term."})});async function q(e){const o=await fetch(e);if(!o.ok)throw new Error("Sorry, there are no images matching your search query. Please try again!");return o.json()}async function h(){const e=new URL("https://pixabay.com/api/"),o=new URLSearchParams(s);e.search=o.toString();try{s.page=p;const{hits:a,totalHits:c}=await q(e,s);if(f=c,a.length===0)d(),g(),l.info({position:"bottomCenter",message:"We're sorry, but there are no results matching your search criteria."});else{const t=a.reduce((i,n)=>i+`<li class="gallery-item">
                <a href=${n.largeImageURL}>
                <img src=${n.webformatURL} class="foto" alt=${n.tags}/>
                </a>
                <div class="benefits">
                <div class="benefit-text">
                <span class="text-value">Likes</span><p class="number">${n.likes}</p></div>
                <div class="benefit-text">
                <span class="text-value">Views</span><p class="number">${n.views}</p></div>
                <div class="benefit-text">
                <span class="text-value">Comments</span><p class="number">${n.comments}</p></div>
                <div class="benefit-text">
                <span class="text-value">Downloads</span><p class="number">${n.downloads}</p></div>
                </div>
            </li>`,"");if(m.innerHTML+=t,new L(".gallery a",{nav:!0,captionDelay:250,captionData:"alt",close:!0,enableKeyboard:!0,docClose:!0}).refresh(),m.querySelector(".gallery-item")){const i=m.querySelector(".gallery-item").getBoundingClientRect().height;if(a.length<u||p*u>=f)d(),g(),l.info({position:"bottomCenter",message:"We're sorry, but you've reached the end of search results."});else{d(),v();const n=2*i;window.scrollBy({top:n,behavior:"smooth"})}}}}catch(a){d(),l.error({position:"bottomCenter",message:a.message})}}function b(){const e=document.querySelector(".loader");e&&(e.style.display="block")}function d(){const e=document.querySelector(".loader");e&&(e.style.display="none")}function v(){const e=document.querySelector(".btn-load-more");e&&(e.style.display="block")}function g(){const e=document.querySelector(".btn-load-more");e&&(e.style.display="none")}
//# sourceMappingURL=commonHelpers.js.map
