import{S as q,i as c,a as S}from"./assets/vendor-bad0427b.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerpolicy&&(o.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?o.credentials="include":t.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function u(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const m=document.getElementById("gallery"),x=document.getElementById("form"),b=document.getElementById("input"),I=document.querySelector(".btn-load-more");document.querySelector(".loader");let y="";const a={key:"41508094-b690cca5e0d97ff8185874dce",q:" ",image_type:"photo",orientation:"horizontal",safesearch:"true",page:1,per_page:40};let C=a.page,p=a.per_page,f;const E=new q(".gallery a",{nav:!0,captionDelay:250,captionData:"alt",close:!0,enableKeyboard:!0,docClose:!0});x.addEventListener("submit",e=>{e.preventDefault();const r=b.value.trim();r?(a.q=r,a.page=1,a.per_page=p,m.innerHTML="",h.length=0,y=r,v(),L(),w()):c.info({position:"bottomCenter",message:"Please enter a search term."})});I.addEventListener("click",e=>{e.preventDefault(),b.value.trim(),y?(L(),a.q=y,a.page+=1,a.per_page=p,v()):c.info({position:"bottomCenter",message:"Please enter a search term."})});async function M(e){try{const r=await S.get(e),{data:s}=r;if(s.total===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");return s}catch{throw new Error("Failed to fetch images data. Please try again!")}}const h=[];async function v(){const e=new URL("https://pixabay.com/api/"),r=new URLSearchParams(a);e.search=r.toString();try{const{hits:s,totalHits:u}=await M(e,a);if(f=u,s.length===0)d(),g(),c.info({position:"bottomCenter",message:"We're sorry, but there are no results matching your search criteria."});else{const t=s.filter(i=>!h.includes(i.webformatURL));h.push(...t.map(i=>i.webformatURL));const o=t.reduce((i,n)=>i+`<li class="gallery-item">
                <a href=${n.largeImageURL}>
                <img src=${n.webformatURL} class="foto" alt=${n.tags}/>
                </a>
                <div class="benefits">
                <div class="benefit-text">
                <span class="text-value">Likes</span><p class="number">${n.likes}</p></div>
                <div class="benefit-text">
                <span class="text-value">Views</span><p class="number">${n.views}</p></div>
                <div class="benefit-text">
                <span class="text-value">Comments</span><p class="number">${n.comments}</p></div>
                <div class="benefit-text">
                <span class="text-value">Downloads</span><p class="number">${n.downloads}</p></div>
                </div>
            </li>`,"");m.innerHTML+=o,E.refresh();const l=m.querySelector(".gallery-item");if(l){const i=l.getBoundingClientRect().height;if(s.length<p||C*p>=f)d(),g(),f===m.querySelectorAll(".gallery-item").length&&g(),c.info({position:"bottomCenter",message:"We're sorry, but you've reached the end of search results."});else{d(),w();const n=2*i;window.scrollBy({top:n,behavior:"smooth"})}}}}catch(s){d(),c.error({position:"bottomCenter",message:s.message})}}function L(){const e=document.querySelector(".loader");e&&(e.style.display="block")}function d(){const e=document.querySelector(".loader");e&&(e.style.display="none")}function w(){const e=document.querySelector(".btn-load-more");e&&(e.style.display="block")}function g(){const e=document.querySelector(".btn-load-more");e&&(e.style.display="none")}
//# sourceMappingURL=commonHelpers.js.map
